AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        STAGE: prod
        InvokePort: 9001
Resources:
  scanWebsite:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: index.handler
      Timeout: 900
      MemorySize: 128
      FunctionName: scanWebsite
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          - lambda:InvokeAsync
          Resource: '*'
      CodeUri: s3://shopint-functions/fee9008af7f2525e548d08b7856c0ccc
