AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        STAGE: prod
        InvokePort: 9002
Resources:
  getSearchResults:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: index.handler
      Timeout: 60
      MemorySize: 128
      FunctionName: getSearchResults
