AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  parseSingleUrlSource:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: index.handler
      Timeout: 60
      MemorySize: 256
      FunctionName: parseSingleUrlSource
      CodeUri: s3://shopint-functions/69402f7d31c7a312e5ea69a6471c06cc
