AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  parseSingleUrlSource:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: index.handler
      Timeout: 60
      MemorySize: 350
      FunctionName: parseSingleUrlSource
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          - lambda:InvokeAsync
          Resource: '*'
      CodeUri: s3://shopint-functions/d3ee375a26a71b8c927e63f91f929b2b
