AWSTemplateFormatVersion : '2010-09-09'
Transform : AWS::Serverless-2016-10-31

Resources:
  scanWebsite:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: index.handler
      Timeout: 60
      MemorySize: 512
      FunctionName: scanWebsite
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - lambda:InvokeAsync
              Resource: "*"